"""update_video

Revision ID: 7fdbe40180f1
Revises: c20598ec94e0
Create Date: 2026-01-06 15:32:59.119930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdbe40180f1'
down_revision: Union[str, None] = 'c20598ec94e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('fps', sa.Integer(), nullable=True))
    op.drop_column('videos', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('videos', 'fps')
    # ### end Alembic commands ###
