"""add uploader to video

Revision ID: ba0dfd7cca85
Revises: d84d96850070
Create Date: 2026-01-07 16:25:37.628691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0dfd7cca85'
down_revision: Union[str, None] = 'd84d96850070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('analysis_results_video_id_fkey', 'analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_results', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.add_column('videos', sa.Column('uploader', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'uploader')
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.create_foreign_key('analysis_results_video_id_fkey', 'analysis_results', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
