"""update_video

Revision ID: c20598ec94e0
Revises: dc093e026cc5
Create Date: 2026-01-06 14:49:56.508321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20598ec94e0'
down_revision: Union[str, None] = 'dc093e026cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'format')
    op.drop_column('videos', 'size')
    # ### end Alembic commands ###
