// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AiAnalyzeApiComparisonsAiAnalyzePostData, AiAnalyzeApiComparisonsAiAnalyzePostErrors, AiAnalyzeApiComparisonsAiAnalyzePostResponses, AnalyzeVideoApiVideosAnalysisPostData, AnalyzeVideoApiVideosAnalysisPostErrors, AnalyzeVideoApiVideosAnalysisPostResponses, DeleteVideoApiVideosDeletePostData, DeleteVideoApiVideosDeletePostErrors, DeleteVideoApiVideosDeletePostResponses, GetAnalysisApiVideosAnalysisGetData, GetAnalysisApiVideosAnalysisGetErrors, GetAnalysisApiVideosAnalysisGetResponses, GetCandidatesApiVideosCandidatesGetData, GetCandidatesApiVideosCandidatesGetErrors, GetCandidatesApiVideosCandidatesGetResponses, GetCategoriesApiCategoriesGetData, GetCategoriesApiCategoriesGetResponses, GetMeApiAuthMeGetData, GetMeApiAuthMeGetResponses, GetPendingVideosApiDashboardPendingVideosGetData, GetPendingVideosApiDashboardPendingVideosGetResponses, GetReportApiComparisonsReportGetData, GetReportApiComparisonsReportGetErrors, GetReportApiComparisonsReportGetResponses, GetStatsApiDashboardStatsGetData, GetStatsApiDashboardStatsGetErrors, GetStatsApiDashboardStatsGetResponses, GetVideoDetailApiVideosDetailGetData, GetVideoDetailApiVideosDetailGetErrors, GetVideoDetailApiVideosDetailGetResponses, GetVideosApiVideosGetData, GetVideosApiVideosGetErrors, GetVideosApiVideosGetResponses, HealthCheckApiHealthGetData, HealthCheckApiHealthGetResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, RegisterApiAuthRegisterPostData, RegisterApiAuthRegisterPostErrors, RegisterApiAuthRegisterPostResponses, RootApiGetData, RootApiGetResponses, UploadVideoApiVideosUploadPostData, UploadVideoApiVideosUploadPostErrors, UploadVideoApiVideosUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register
 *
 * Register a new user.
 */
export const registerApiAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterApiAuthRegisterPostResponses, RegisterApiAuthRegisterPostErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 *
 * Authenticate user and return token.
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Me
 *
 * Get current authenticated user.
 */
export const getMeApiAuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeApiAuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<GetMeApiAuthMeGetResponses, unknown, ThrowOnError>({ url: '/api/auth/me', ...options });

/**
 * Get Videos
 */
export const getVideosApiVideosGet = <ThrowOnError extends boolean = false>(options?: Options<GetVideosApiVideosGetData, ThrowOnError>) => (options?.client ?? client).get<GetVideosApiVideosGetResponses, GetVideosApiVideosGetErrors, ThrowOnError>({ url: '/api/videos', ...options });

/**
 * Get Candidates
 */
export const getCandidatesApiVideosCandidatesGet = <ThrowOnError extends boolean = false>(options?: Options<GetCandidatesApiVideosCandidatesGetData, ThrowOnError>) => (options?.client ?? client).get<GetCandidatesApiVideosCandidatesGetResponses, GetCandidatesApiVideosCandidatesGetErrors, ThrowOnError>({ url: '/api/videos/candidates', ...options });

/**
 * Get Video Detail
 */
export const getVideoDetailApiVideosDetailGet = <ThrowOnError extends boolean = false>(options: Options<GetVideoDetailApiVideosDetailGetData, ThrowOnError>) => (options.client ?? client).get<GetVideoDetailApiVideosDetailGetResponses, GetVideoDetailApiVideosDetailGetErrors, ThrowOnError>({ url: '/api/videos/detail', ...options });

/**
 * Upload Video
 */
export const uploadVideoApiVideosUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadVideoApiVideosUploadPostData, ThrowOnError>) => (options.client ?? client).post<UploadVideoApiVideosUploadPostResponses, UploadVideoApiVideosUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/videos/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Video
 */
export const deleteVideoApiVideosDeletePost = <ThrowOnError extends boolean = false>(options: Options<DeleteVideoApiVideosDeletePostData, ThrowOnError>) => (options.client ?? client).post<DeleteVideoApiVideosDeletePostResponses, DeleteVideoApiVideosDeletePostErrors, ThrowOnError>({ url: '/api/videos/delete', ...options });

/**
 * Get Analysis
 */
export const getAnalysisApiVideosAnalysisGet = <ThrowOnError extends boolean = false>(options: Options<GetAnalysisApiVideosAnalysisGetData, ThrowOnError>) => (options.client ?? client).get<GetAnalysisApiVideosAnalysisGetResponses, GetAnalysisApiVideosAnalysisGetErrors, ThrowOnError>({ url: '/api/videos/analysis', ...options });

/**
 * Analyze Video
 */
export const analyzeVideoApiVideosAnalysisPost = <ThrowOnError extends boolean = false>(options: Options<AnalyzeVideoApiVideosAnalysisPostData, ThrowOnError>) => (options.client ?? client).post<AnalyzeVideoApiVideosAnalysisPostResponses, AnalyzeVideoApiVideosAnalysisPostErrors, ThrowOnError>({ url: '/api/videos/analysis', ...options });

/**
 * Get Categories
 */
export const getCategoriesApiCategoriesGet = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesApiCategoriesGetData, ThrowOnError>) => (options?.client ?? client).get<GetCategoriesApiCategoriesGetResponses, unknown, ThrowOnError>({ url: '/api/categories', ...options });

/**
 * Get Stats
 */
export const getStatsApiDashboardStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatsApiDashboardStatsGetData, ThrowOnError>) => (options?.client ?? client).get<GetStatsApiDashboardStatsGetResponses, GetStatsApiDashboardStatsGetErrors, ThrowOnError>({ url: '/api/dashboard/stats', ...options });

/**
 * Get Pending Videos
 */
export const getPendingVideosApiDashboardPendingVideosGet = <ThrowOnError extends boolean = false>(options?: Options<GetPendingVideosApiDashboardPendingVideosGetData, ThrowOnError>) => (options?.client ?? client).get<GetPendingVideosApiDashboardPendingVideosGetResponses, unknown, ThrowOnError>({ url: '/api/dashboard/pending-videos', ...options });

/**
 * Ai Analyze
 */
export const aiAnalyzeApiComparisonsAiAnalyzePost = <ThrowOnError extends boolean = false>(options: Options<AiAnalyzeApiComparisonsAiAnalyzePostData, ThrowOnError>) => (options.client ?? client).post<AiAnalyzeApiComparisonsAiAnalyzePostResponses, AiAnalyzeApiComparisonsAiAnalyzePostErrors, ThrowOnError>({
    url: '/api/comparisons/ai-analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Report
 */
export const getReportApiComparisonsReportGet = <ThrowOnError extends boolean = false>(options: Options<GetReportApiComparisonsReportGetData, ThrowOnError>) => (options.client ?? client).get<GetReportApiComparisonsReportGetResponses, GetReportApiComparisonsReportGetErrors, ThrowOnError>({ url: '/api/comparisons/report', ...options });

/**
 * Health Check
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Root
 */
export const rootApiGet = <ThrowOnError extends boolean = false>(options?: Options<RootApiGetData, ThrowOnError>) => (options?.client ?? client).get<RootApiGetResponses, unknown, ThrowOnError>({ url: '/api/', ...options });
