// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8800' | (string & {});
};

/**
 * AIAnalyzeRequest
 */
export type AiAnalyzeRequest = {
    /**
     * Video A Id
     */
    video_a_id: string;
    /**
     * Video B Id
     */
    video_b_id: string;
};

/**
 * AnalysisResponse
 */
export type AnalysisResponse = {
    video: VideoDetailResponse;
    analysis?: AnalysisResultResponse | null;
};

/**
 * AnalysisResultResponse
 */
export type AnalysisResultResponse = {
    /**
     * Marked Path
     */
    marked_path?: string | null;
    /**
     * Start Time
     */
    start_time?: number | null;
    /**
     * End Time
     */
    end_time?: number | null;
    /**
     * Init Speed
     */
    init_speed?: number | null;
    /**
     * Avg Speed
     */
    avg_speed?: number | null;
    /**
     * Curve Data
     */
    curve_data?: Array<unknown> | null;
    /**
     * Processed At
     */
    processed_at?: string | null;
    /**
     * Marked Url
     */
    marked_url?: string | null;
};

/**
 * BaseResponse[AnalysisResponse]
 */
export type BaseResponseAnalysisResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: AnalysisResponse;
};

/**
 * BaseResponse[ComparisonReportResponse]
 */
export type BaseResponseComparisonReportResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: ComparisonReportResponse;
};

/**
 * BaseResponse[List[CategoryResponse]]
 */
export type BaseResponseListCategoryResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    /**
     * Data
     */
    data: Array<CategoryResponse>;
};

/**
 * BaseResponse[List[PendingVideoGroup]]
 */
export type BaseResponseListPendingVideoGroup = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    /**
     * Data
     */
    data: Array<PendingVideoGroup>;
};

/**
 * BaseResponse[LoginResponse]
 */
export type BaseResponseLoginResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: LoginResponse;
};

/**
 * BaseResponse[StatsData]
 */
export type BaseResponseStatsData = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: StatsData;
};

/**
 * BaseResponse[UploadResponse]
 */
export type BaseResponseUploadResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: UploadResponse;
};

/**
 * BaseResponse[UserListResponse]
 */
export type BaseResponseUserListResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: UserListResponse;
};

/**
 * BaseResponse[UserResponse]
 */
export type BaseResponseUserResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: UserResponse;
};

/**
 * BaseResponse[VideoDetailResponse]
 */
export type BaseResponseVideoDetailResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: VideoDetailResponse;
};

/**
 * BaseResponse[VideoListResponse]
 */
export type BaseResponseVideoListResponse = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: VideoListResponse;
};

/**
 * BaseResponse[dict]
 */
export type BaseResponseDict = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * Body_upload_video_api_videos_upload_post
 */
export type BodyUploadVideoApiVideosUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Title
     */
    title?: string;
    /**
     * Category Id
     */
    category_id?: number;
};

/**
 * CategoryResponse
 */
export type CategoryResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ComparisonReportResponse
 */
export type ComparisonReportResponse = {
    /**
     * Video A Id
     */
    video_a_id: string;
    /**
     * Video B Id
     */
    video_b_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Ai Analysis
     */
    ai_analysis?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginData
 */
export type LoginData = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token
     */
    token: string;
    user: UserResponse;
};

/**
 * PendingVideoGroup
 */
export type PendingVideoGroup = {
    /**
     * Date
     */
    date: string;
    /**
     * List
     */
    list: Array<VideoResponse>;
};

/**
 * SetRoleRequest
 */
export type SetRoleRequest = {
    /**
     * Role
     */
    role: string;
};

/**
 * StatsData
 */
export type StatsData = {
    /**
     * Total
     */
    total: number;
    /**
     * Completed
     */
    completed: number;
    /**
     * Pending
     */
    pending: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Processing
     */
    processing: number;
};

/**
 * UpdatePasswordRequest
 */
export type UpdatePasswordRequest = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: number;
    /**
     * Raw Url
     */
    raw_url: string;
    /**
     * Thumbnail Url
     */
    thumbnail_url?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserListResponse
 */
export type UserListResponse = {
    /**
     * Items
     */
    items: Array<UserResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoDetailResponse
 */
export type VideoDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Fps
     */
    fps?: number | null;
    status: VideoStatus;
    /**
     * Uploader
     */
    uploader?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Log
     */
    error_log?: string | null;
    /**
     * Url
     */
    readonly url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * VideoListResponse
 */
export type VideoListResponse = {
    /**
     * Items
     */
    items: Array<VideoResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * VideoResponse
 */
export type VideoResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Fps
     */
    fps?: number | null;
    status: VideoStatus;
    /**
     * Uploader
     */
    uploader?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Url
     */
    readonly url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * VideoStatus
 */
export type VideoStatus = 0 | 1 | 2 | 3;

/**
 * AnalysisResponse
 */
export type AnalysisResponseWritable = {
    video: VideoDetailResponseWritable;
    analysis?: AnalysisResultResponse | null;
};

/**
 * BaseResponse[AnalysisResponse]
 */
export type BaseResponseAnalysisResponseWritable = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: AnalysisResponseWritable;
};

/**
 * BaseResponse[List[PendingVideoGroup]]
 */
export type BaseResponseListPendingVideoGroupWritable = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    /**
     * Data
     */
    data: Array<PendingVideoGroupWritable>;
};

/**
 * BaseResponse[VideoDetailResponse]
 */
export type BaseResponseVideoDetailResponseWritable = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: VideoDetailResponseWritable;
};

/**
 * BaseResponse[VideoListResponse]
 */
export type BaseResponseVideoListResponseWritable = {
    /**
     * Code
     *
     * 状态码
     */
    code: number;
    /**
     * Err Msg
     *
     * 错误信息
     */
    err_msg: string;
    data: VideoListResponseWritable;
};

/**
 * PendingVideoGroup
 */
export type PendingVideoGroupWritable = {
    /**
     * Date
     */
    date: string;
    /**
     * List
     */
    list: Array<VideoResponseWritable>;
};

/**
 * VideoDetailResponse
 */
export type VideoDetailResponseWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Fps
     */
    fps?: number | null;
    status: VideoStatus;
    /**
     * Uploader
     */
    uploader?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Log
     */
    error_log?: string | null;
};

/**
 * VideoListResponse
 */
export type VideoListResponseWritable = {
    /**
     * Items
     */
    items: Array<VideoResponseWritable>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * VideoResponse
 */
export type VideoResponseWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Category Id
     */
    category_id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Fps
     */
    fps?: number | null;
    status: VideoStatus;
    /**
     * Uploader
     */
    uploader?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

export type LoginApiAuthLoginPostData = {
    body: LoginData;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseLoginResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type GetMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUserResponse;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type UpdatePasswordApiUserPasswordPostData = {
    body: UpdatePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/user/password';
};

export type UpdatePasswordApiUserPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordApiUserPasswordPostError = UpdatePasswordApiUserPasswordPostErrors[keyof UpdatePasswordApiUserPasswordPostErrors];

export type UpdatePasswordApiUserPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUserResponse;
};

export type UpdatePasswordApiUserPasswordPostResponse = UpdatePasswordApiUserPasswordPostResponses[keyof UpdatePasswordApiUserPasswordPostResponses];

export type GetProfileApiUserProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type GetProfileApiUserProfileGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUserResponse;
};

export type GetProfileApiUserProfileGetResponse = GetProfileApiUserProfileGetResponses[keyof GetProfileApiUserProfileGetResponses];

export type GetUsersApiAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Keyword
         */
        keyword?: string;
        /**
         * Role
         */
        role?: string;
    };
    url: '/api/admin/users';
};

export type GetUsersApiAdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiAdminUsersGetError = GetUsersApiAdminUsersGetErrors[keyof GetUsersApiAdminUsersGetErrors];

export type GetUsersApiAdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUserListResponse;
};

export type GetUsersApiAdminUsersGetResponse = GetUsersApiAdminUsersGetResponses[keyof GetUsersApiAdminUsersGetResponses];

export type CreateUserAdminApiAdminUsersCreatePostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/admin/users/create';
};

export type CreateUserAdminApiAdminUsersCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserAdminApiAdminUsersCreatePostError = CreateUserAdminApiAdminUsersCreatePostErrors[keyof CreateUserAdminApiAdminUsersCreatePostErrors];

export type CreateUserAdminApiAdminUsersCreatePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type CreateUserAdminApiAdminUsersCreatePostResponse = CreateUserAdminApiAdminUsersCreatePostResponses[keyof CreateUserAdminApiAdminUsersCreatePostResponses];

export type DeleteUserAdminApiAdminUsersDeletePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/admin/users/delete';
};

export type DeleteUserAdminApiAdminUsersDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserAdminApiAdminUsersDeletePostError = DeleteUserAdminApiAdminUsersDeletePostErrors[keyof DeleteUserAdminApiAdminUsersDeletePostErrors];

export type DeleteUserAdminApiAdminUsersDeletePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type DeleteUserAdminApiAdminUsersDeletePostResponse = DeleteUserAdminApiAdminUsersDeletePostResponses[keyof DeleteUserAdminApiAdminUsersDeletePostResponses];

export type SetRoleApiAdminUsersSetRolePostData = {
    body: SetRoleRequest;
    path?: never;
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/admin/users/set-role';
};

export type SetRoleApiAdminUsersSetRolePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRoleApiAdminUsersSetRolePostError = SetRoleApiAdminUsersSetRolePostErrors[keyof SetRoleApiAdminUsersSetRolePostErrors];

export type SetRoleApiAdminUsersSetRolePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type SetRoleApiAdminUsersSetRolePostResponse = SetRoleApiAdminUsersSetRolePostResponses[keyof SetRoleApiAdminUsersSetRolePostResponses];

export type GetVideosApiVideosGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Keyword
         */
        keyword?: string;
        /**
         * Category Id
         */
        category_id?: number;
        /**
         * Status
         */
        status?: number;
    };
    url: '/api/videos';
};

export type GetVideosApiVideosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideosApiVideosGetError = GetVideosApiVideosGetErrors[keyof GetVideosApiVideosGetErrors];

export type GetVideosApiVideosGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseVideoListResponse;
};

export type GetVideosApiVideosGetResponse = GetVideosApiVideosGetResponses[keyof GetVideosApiVideosGetResponses];

export type GetCandidatesApiVideosCandidatesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Keyword
         */
        keyword?: string;
        /**
         * Category Id
         */
        category_id?: number;
    };
    url: '/api/videos/candidates';
};

export type GetCandidatesApiVideosCandidatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCandidatesApiVideosCandidatesGetError = GetCandidatesApiVideosCandidatesGetErrors[keyof GetCandidatesApiVideosCandidatesGetErrors];

export type GetCandidatesApiVideosCandidatesGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseVideoListResponse;
};

export type GetCandidatesApiVideosCandidatesGetResponse = GetCandidatesApiVideosCandidatesGetResponses[keyof GetCandidatesApiVideosCandidatesGetResponses];

export type GetVideoDetailApiVideosDetailGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/videos/detail';
};

export type GetVideoDetailApiVideosDetailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoDetailApiVideosDetailGetError = GetVideoDetailApiVideosDetailGetErrors[keyof GetVideoDetailApiVideosDetailGetErrors];

export type GetVideoDetailApiVideosDetailGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseVideoDetailResponse;
};

export type GetVideoDetailApiVideosDetailGetResponse = GetVideoDetailApiVideosDetailGetResponses[keyof GetVideoDetailApiVideosDetailGetResponses];

export type UploadVideoApiVideosUploadPostData = {
    body: BodyUploadVideoApiVideosUploadPost;
    path?: never;
    query?: never;
    url: '/api/videos/upload';
};

export type UploadVideoApiVideosUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoApiVideosUploadPostError = UploadVideoApiVideosUploadPostErrors[keyof UploadVideoApiVideosUploadPostErrors];

export type UploadVideoApiVideosUploadPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUploadResponse;
};

export type UploadVideoApiVideosUploadPostResponse = UploadVideoApiVideosUploadPostResponses[keyof UploadVideoApiVideosUploadPostResponses];

export type DeleteVideoApiVideosDeletePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/videos/delete';
};

export type DeleteVideoApiVideosDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVideoApiVideosDeletePostError = DeleteVideoApiVideosDeletePostErrors[keyof DeleteVideoApiVideosDeletePostErrors];

export type DeleteVideoApiVideosDeletePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type DeleteVideoApiVideosDeletePostResponse = DeleteVideoApiVideosDeletePostResponses[keyof DeleteVideoApiVideosDeletePostResponses];

export type GetAnalysisApiVideosAnalysisGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/videos/analysis';
};

export type GetAnalysisApiVideosAnalysisGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisApiVideosAnalysisGetError = GetAnalysisApiVideosAnalysisGetErrors[keyof GetAnalysisApiVideosAnalysisGetErrors];

export type GetAnalysisApiVideosAnalysisGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseAnalysisResponse;
};

export type GetAnalysisApiVideosAnalysisGetResponse = GetAnalysisApiVideosAnalysisGetResponses[keyof GetAnalysisApiVideosAnalysisGetResponses];

export type AnalyzeVideoApiVideosAnalysisPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/videos/analysis';
};

export type AnalyzeVideoApiVideosAnalysisPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeVideoApiVideosAnalysisPostError = AnalyzeVideoApiVideosAnalysisPostErrors[keyof AnalyzeVideoApiVideosAnalysisPostErrors];

export type AnalyzeVideoApiVideosAnalysisPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type AnalyzeVideoApiVideosAnalysisPostResponse = AnalyzeVideoApiVideosAnalysisPostResponses[keyof AnalyzeVideoApiVideosAnalysisPostResponses];

export type GetCategoriesApiCategoriesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type GetCategoriesApiCategoriesGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseListCategoryResponse;
};

export type GetCategoriesApiCategoriesGetResponse = GetCategoriesApiCategoriesGetResponses[keyof GetCategoriesApiCategoriesGetResponses];

export type GetStatsApiDashboardStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/stats';
};

export type GetStatsApiDashboardStatsGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseStatsData;
};

export type GetStatsApiDashboardStatsGetResponse = GetStatsApiDashboardStatsGetResponses[keyof GetStatsApiDashboardStatsGetResponses];

export type GetVideosApiDashboardVideosGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: VideoStatus | null;
    };
    url: '/api/dashboard/videos';
};

export type GetVideosApiDashboardVideosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideosApiDashboardVideosGetError = GetVideosApiDashboardVideosGetErrors[keyof GetVideosApiDashboardVideosGetErrors];

export type GetVideosApiDashboardVideosGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseListPendingVideoGroup;
};

export type GetVideosApiDashboardVideosGetResponse = GetVideosApiDashboardVideosGetResponses[keyof GetVideosApiDashboardVideosGetResponses];

export type AiAnalyzeApiComparisonsAiAnalyzePostData = {
    body: AiAnalyzeRequest;
    path?: never;
    query?: never;
    url: '/api/comparisons/ai-analyze';
};

export type AiAnalyzeApiComparisonsAiAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiAnalyzeApiComparisonsAiAnalyzePostError = AiAnalyzeApiComparisonsAiAnalyzePostErrors[keyof AiAnalyzeApiComparisonsAiAnalyzePostErrors];

export type AiAnalyzeApiComparisonsAiAnalyzePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseComparisonReportResponse;
};

export type AiAnalyzeApiComparisonsAiAnalyzePostResponse = AiAnalyzeApiComparisonsAiAnalyzePostResponses[keyof AiAnalyzeApiComparisonsAiAnalyzePostResponses];

export type GetReportApiComparisonsReportGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Video A Id
         */
        video_a_id: string;
        /**
         * Video B Id
         */
        video_b_id: string;
    };
    url: '/api/comparisons/report';
};

export type GetReportApiComparisonsReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportApiComparisonsReportGetError = GetReportApiComparisonsReportGetErrors[keyof GetReportApiComparisonsReportGetErrors];

export type GetReportApiComparisonsReportGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseComparisonReportResponse;
};

export type GetReportApiComparisonsReportGetResponse = GetReportApiComparisonsReportGetResponses[keyof GetReportApiComparisonsReportGetResponses];

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/';
};

export type RootApiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
